### ISSUE TITLE
可以把`subtitle`里打印显示的文本换为动态从‘一言’接口获取的文本吗？

### ISSUE THREAD

**Issue by Hodge-Zhang** [Shen-Yu/hexo-theme-ayer#102]
目前版本的Ayer里主页背景的打印特效的文字是通过_config.yml文件来配置的，最长是3个text：
```
subtitle:
  enable: true # 是否开启动效
  text: 面朝大海，心暖花开。 # 显示的文字
  # text2: 愿你一生努力，一生被爱 # 滚动播放，如果不需要可以留空
  # text3: 想要的都拥有，得不到的都释怀 # 最多支持三段文字
  startDelay: 200 # 延迟时间
  typeSpeed: 200 # 打字速度
  loop: true # 是否循环
  backSpeed: 100 # 回退速度
  showCursor: true # 是否显示光标
```
那么这里的文本可以通过一言接口来获得吗？比如`fetch(https://v1.hitokoto.cn/?c=d&c=i&c=k&encode=text)`，然后把文本填入到参数`strings: ['<%= theme.subtitle.text %>', '<%= theme.subtitle.text2 %>', '<%= theme.subtitle.text3 %>'],`这里。
我并没有学过js，对fetch获得的对象的处理并不了解，也没有见到hexo相关主题有这样做的，这样是否可行，如果可行烦请作者大大给出一个可行的方案。
