### ISSUE TITLE
关于网站部署在二级目录导致配置的图片访问不到,search.js同样访问不到的问题

### ISSUE THREAD

**Issue by resticDOG** [Shen-Yu/hexo-theme-ayer#55]
**同上:**
- hexo配置:
```yml
url: https://resticdog.github.io/linkzz/
root: /linkzz/
```
`$ hexo server`
之后访问localhost:4000/linkzz/ ,封面图,logo这些图片都是根路径**localhost:4000/images/ayer.svg**
而不是**localhost:4000/linkzz/images/ayer.svg**, 不知是否是主题的问题,还是我配置有误?

**Comment by resticDOG** [comment]
对了,补上主题配置:
```yml
cover:
  enable: true
  path: /images/cover1.jpg 
  logo: /images/ayer.svg 
```
