### ISSUE TITLE
Katex没有生效

### ISSUE THREAD

**Issue by wangwei1237** [Shen-Yu/hexo-theme-ayer#58]
按照如下的配置试用了下Katex来渲染LaTex数学公式，发现没有生效呢。

```
# 数学公式
mathjax: false

# Katex数学公式(allpost设置为false时只有头部设置math:true的文章才开启)
katex:
  enable: true # true
  allpost: true
  copy_tex: true
```
