### ISSUE TITLE
文章名字，以及文件夹名字，上传到deploy github上，有的大写变小写？

### ISSUE THREAD

**Issue by pxim** [Shen-Yu/hexo-theme-ayer#69]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Actual behavior 

- Links to demo site with this issue: N/A  https://pxim.github.io/2020/05/25/software/%E3%80%90Software%E3%80%91%E5%BC%80%E5%8F%91%E8%BE%85%E5%8A%A9%E5%B7%A5%E5%85%B7/
- Links to repository or source code of the blog: N/A  https://github.com/pxim/pxim.github.io/tree/master/2020/05/25/software/%E3%80%90software%E3%80%91%E5%BC%80%E5%8F%91%E8%BE%85%E5%8A%A9%E5%B7%A5%E5%85%B7

## Steps to reproduce the behavior 

1. N/A clean
2. N/A build
3. N/A deploy

### Node.js and NPM Information

```

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server",
    "generate": "hexo generate"
  },
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "git": "^0.1.5",
    "hexo": "^4.2.1",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.3.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

```

### HTML Configuration

```

```

### MiniValine Configuration

```
# 3、MiniValine
# See: https://github.com/MiniValine/MiniValine
minivaline:
  enable: false
  mode: DesertsP # DesertsP or xCss
  placeholder: Write a Comment # Comment box placeholder
  math: true # Support MathJax.
  md: true # Support Markdown.
  enableQQ: false # Enable QQ avatar API.
  NoRecordIP: false # Do not record commenter IP.
  visitor: true # Article reading statistics.
  maxNest: 6 # Sub-comment maximum nesting depth.
  pageSize: 6 # Pagination size.
  adminEmailMd5: de8a7aa53d07e6b6bceb45c64027763d # The MD5 of Admin Email to show Admin Flag.[Just Only DesertsP Style mode]
  tagMeta: # The String Array of Words to show Flag.[Just Only xCss Style mode]
    - 管理员
    - 小伙伴
    - 访客
  master: # The MD5 String Array of master Email to show master Flag.[Just Only xCss Style mode]
    - de8a7aa53d07e6b6bceb45c64027763d
  friends: # The MD5 String Array of friends Email to show friends Flag.[Just Only xCss Style mode]
    - https://kalasearch.cn/
    - adb7d1cd192658a55c0ad22a3309cecf
    - 3ce1e6c77b4910f1871106cb30dc62b0
    - cfce8dc43725cc14ffcd9fb4892d5bfc
  # MiniValine's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en  | zh-CN | (and many more)
  # More i18n info: https://github.com/MiniValine/minivaline-i18n
  lang:
  # Expression Url.
  # https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-customize-emoticons
  emoticonUrl:
    - https://cdn.jsdelivr.net/npm/alus@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/qq@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/Bilibilis@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/tieba@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/twemoji@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/weibo@latest
```

## Other Information 

![5`S6RMQY {~~PY}P5W8VEB](https://user-images.githubusercontent.com/5111701/87370908-c222c600-c5b6-11ea-9f05-699ca94e6a64.png)

为什么我本地是大写，上传到deploy github上就变成小写了，而且不是一定的，有的会变，有的不会变；
